###############################################################################
# Author: Mohammad Mostafanejad                                               #
# Date: August 2025                                                           #
# Description:                                                                #
# Script for standardization of the SMILES using ChEMBL standardization       #
# pipeline: [Bento et al. J Cheminform 12 (2020)].                            #
# SMILES are taken from a cleaned up version of PubChem (version 04-18-2024)  #
# dataset, processed by the 'pubchem04182025_cleaner.py' script.              #
###############################################################################

# import the necessary modules
from rdkit import Chem
from rdkit import RDLogger  # to disable the RDKit warnings

RDLogger.DisableLog("rdApp.*")  # disable the RDKit warnings
from chembl_structure_pipeline.standardizer import standardize_mol
from datasets import load_from_disk

# set the main variables
input_data_path = "/D3/sina/data/pubchem04182025_isostereomers_tokenized_cleaned"
output_data_path = (
    "/D3/sina/data/pubchem04182025_isostereomers_tokenized_and_chemblized"
)


# a batch version of the chembl standardizer
def chembl_standardizer_batch(smi: str) -> dict:
    """Standardize a batch of SMILES using the ChEMBL standardization pipeline.

    Parameters
    ----------
    smiles : str
        A SMILES string to be standardized.

    Returns
    -------
    dict
        A dictionary containing the standardized SMILES strings and their corresponding InChI and InChIKey.
    """
    inchi = ""
    inchikey = ""
    std_smi = ""
    std_inchi = ""
    std_inchikey = ""
    mol = Chem.MolFromSmiles(smi, sanitize=False)
    if mol:
        try:
            inchi = Chem.MolToInchi(
                mol, options="", logLevel=None, treatWarningAsError=False
            )
            inchikey = Chem.MolToInchiKey(mol, options="")
            # standardize the molecule
            std_mol = standardize_mol(mol, check_exclusion=True, sanitize=False)
            std_inchi = Chem.MolToInchi(
                std_mol, options="", logLevel=None, treatWarningAsError=False
            )
            std_inchikey = Chem.MolToInchiKey(std_mol, options="")
            std_smi = Chem.MolToSmiles(
                std_mol,
                isomericSmiles=True,
                kekuleSmiles=False,
                rootedAtAtom=-1,
                canonical=True,
                allBondsExplicit=False,
                allHsExplicit=False,
            )
        except Exception as e:
            print(f"Error standardizing SMILES {smi}: {e}")
    else:
        raise ValueError(f"Invalid SMILES: {smi}")

    return {
        "original_SMILES": smi,
        "original_InChI": inchi,
        "original_InChIKey": inchikey,
        "SMILES": std_smi,
        "InChI": std_inchi,
        "InChIKey": std_inchikey,
        "problematic_SMILES": smi if mol is None else "",
    }


def main():
    # load the dataset
    ds = load_from_disk(input_data_path)

    # standardize the SMILES in batches of batch_size.
    # NOTE: we remove the input_ids and attention_mask columns
    # as they are generated by the wordpiece tokenizer based on
    # pubchem standardization pipeline. After standardization
    # using chembl pipeline, the tokenization should be redone.
    ds_pugged = ds.map(
        chembl_standardizer_batch,
        batched=False,
        input_columns=["smiles"],
        num_proc=64,
        remove_columns=[
            "smiles",
            "input_ids",
            "attention_mask",
        ],
    )

    # save the dataset
    ds_pugged.save_to_disk(output_data_path)


if __name__ == "__main__":
    main()
