dirs:
  cache_dir: "${dirs.default_root_dir}/tmp"
  default_root_dir: "/D2/sina/pubchem_finetune/${model.model_name}"
data:
  date: ${now:%Y-%m-%d_%H-%M-%S}
  dataset_path: "/D2/sina/data/pubchemqc_b3lyp_tokenized"
  label_column: "energy-alpha-gap"
  num_workers: 63
  test_size: 0.2
model:
  model_name: ???
  pretrained_model_name_or_path: "/D2/sina/pubchem_finetune/berttiny-ms-1234-ds-1234/tmp/gen-cismi-berttiny-wordpiece"
  token: ${oc.env:HF_TOKEN}
  stack_depth: 1
  p: 0.5
trainer:
  lr: 5e-5
  weight_decay: 0.01
  num_epochs: 10
  log_every_n_steps: 10
  batch_size: 128
  deterministic: True
  precision: "16-mixed"
  accelerator: "gpu"
  strategy: "ddp"
  devices: 2
  num_nodes: 1
  lr_scheduler: null
  seed: 1234
callbacks:
  lr_monitor:
    logging_interval: "step"
    log_momentum: False
    log_weight_decay: False
  early_stopping:
    monitor: "val/loss"
    min_delta: 0.00
    patience: 3
    verbose: True
    mode: "min"
loggers:
  logger: "wandb"
  tensorboard:
    name: ${model.model_name}-${data.date}
    save_dir: ${dirs.default_root_dir}/tensorboard
    sub_dir: null
  wandb:
    wandb_project: bertology
    wandb_entity: molssi-bert
    wandb_username: "sina-mostafanejad"
    wandb_user_email: "sina.mostafanejad@gmail.com"
    wandb_name: ${model.model_name}-${data.date}
    wandb_job_name: ${model.model_name}
    wandb_job_type: "finetuning"
    wandb_run_group: "finetune"
    wandb_tags: manuscript,finetuning
    wandb_dir: ${dirs.default_root_dir}/wandb
    wandb_cache_dir: ${loggers.wandb.wandb_dir}/wandb_cache
    wandb_data_dir: ${loggers.wandb.wandb_dir}/data_stage
    wandb_artifact_dir: ${loggers.wandb.wandb_dir}/artifacts
    wandb_api_key: ${oc.env:WANDB_API_KEY}
    wandb_watch: "all"
    wandb_log_model: True
    wandb_run_id: null
    wandb_resume: False
    wandb_offline: False
    wandb_prefix: null
    wandb_log_freq: 300