###############################################################################
# Author: Mohammad Mostafanejad                                               #
# Date: May 2025                                                              #
# Description:                                                                #
# This script uses the pre-trained tokenizer (generated by                    #
# the pubchem_tokenizer_training.py) to tokenize the PubChem canonical        #
# isomeric SMILES written in the pubchem_isostereosmiles.txt (generated by    #
# the pubchem_cismi_writer.py) script. The tokenized dataset is saved to      #
# the disk for later use in pre-training a BERT model.                        #
###############################################################################

# import necessary libraries
from datasets import load_dataset
from transformers import PreTrainedTokenizerFast

# set global variables
input_data_file = "./pubchem_isostereosmiles.txt"
data_output_dir = "./tmp/pubchem04182025_isostereomers_tokenized"
tokenizer_name = "gen-mlm-cismi-bert-wordpiece-pubchem04182025"

# load the fast tokenizer
fast_tokenizer = PreTrainedTokenizerFast(
    tokenizer_file=f"./{tokenizer_name}/tokenizer.json"
)

# set the fast tokenizer's attributes
fast_tokenizer.model_max_length = 512
fast_tokenizer.name_or_path = tokenizer_name

# set special tokens
fast_tokenizer.pad_token = "[PAD]"
fast_tokenizer.unk_token = "[UNK]"
fast_tokenizer.cls_token = "[CLS]"
fast_tokenizer.sep_token = "[SEP]"
fast_tokenizer.mask_token = "[MASK]"

# load the dataset
ds_dict = load_dataset(
    "text", data_files=input_data_file, split="train", cache_dir="./tmp"
)

# rename the column
ds_dict = ds_dict.rename_column("text", "smiles")


# define the tokenize function
def tokenize_function(smiles):
    return fast_tokenizer(
        smiles["smiles"], truncation=True, padding="max_length", max_length=512
    )


# tokenize the dataset and remove the token_type_ids column as it is not needed
pt_tokenized_ds_dict = ds_dict.map(
    tokenize_function,
    batched=True,
    batch_size=2048,
    num_proc=4,
).remove_columns("token_type_ids")

# save the tokenized dataset
pt_tokenized_ds_dict.save_to_disk(data_output_dir)
